### ISSUE TITLE
BUG: Merging: Teacher can rename self reported student to name of other self reported student

### ISSUE THREAD

**Issue by rauwuckl** [klassenteiler/Klassenteiler#49]
there are self reported students: Clemens, Anna

the teacher renames:
Clemens -> Anna

(currently then Anna and Clemens get merged. The outgoing relationships of Anna get ignored)

Not sure if this is desired

**Comment by rauwuckl** [comment]
also I can send

delete: Clemens
add: Clemens

this potentially should throw an error as well

**Comment by antonlaukemper** [comment]
> there are self reported students: Clemens, Anna
> 
> the teacher renames:
> Clemens -> Anna

this should be handled in the front-end because it would be a mistake by the teacher, right? There is no legitimate way for two self-reported students that refer to the same student to exist.

**Comment by antonlaukemper** [comment]
> delete: Clemens
> add: Clemens
> 
> this potentially should throw an error as well

yeah I'm working on the input checks in the backend now

**Comment by rauwuckl** [comment]
all of this things should also be handled in the front-end, but arguably the backend should also throw an error if they are tried

**Comment by antonlaukemper** [comment]
the second issue is covered, simply because adding a self-reported student that already exists fails. The controller gives a 400 status if that happens. The first case is a bit annoying to handle because I would need to check whether the student found via hash has self-reported set to true. I can do that if needed, but I would say, we don't :D

**Comment by rauwuckl** [comment]
done
